version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=medsight
    ports:
      - "5432:5432"
    networks:
      - medirekor-network
    volumes:
      - ./init-scripts/:/docker-entrypoint-initdb.d/

  medirekor-core-api:
    image: medirekor-backend
    tty: true
    build:
      context: ./docker/backend
      dockerfile: ./dockerfile
    environment:
      - POSTGRES_NAME=db
      - POSTGRES_PORT=5432
    ports:
      - "3001:3001"
    networks:
      - medirekor-network
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - db

networks:
  medirekor-network:
    driver: bridge
