export enum InternalCodes {
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    USER_DUPLICATED = 'USER_DUPLICATED',
    USER_IS_NOT_PENDING = 'USER_IS_NOT_PENDING',
    USER_IS_NOT_ACTIVATED = 'USER_IS_NOT_ACTIVATED',
    PASSWORDS_NOT_EQUALS = 'PASSWORDS_NOT_EQUALS',
    SETTING_NOT_FOUND = 'SETTING_NOT_FOUND',
    ORGANIZATION_TO_SETTING_DUPLICATED = 'ORGANIZATION_TO_SETTING_DUPLICATED',
    ORGANIZATION_TO_SETTING_WRONG_TYPE = 'ORGANIZATION_TO_SETTING_WRONG_TYPE',
    ORGANIZATION_TO_SETTING_NOT_FOUND = 'ORGANIZATION_TO_SETTING_NOT_FOUND',
    ORGANIZATION_NOT_FOUND = 'ORGANIZATION_NOT_FOUND',
}

export enum StatusCodes {
    OK = 200,
    BAD_INPUT = 400,
    UNAUTHORIZED = 401,
    FORBIDDEN = 403,
    NOT_FOUND = 404,
    UNPROCESSABLE_ENTITY = 422,
    INTERNAL_SERVER_ERROR = 500,
}