export enum InternalCodes {
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    USER_DUPLICATED = 'USER_DUPLICATED',
    USER_IS_NOT_PENDING = 'USER_IS_NOT_PENDING',
    USER_IS_NOT_ACTIVATED = 'USER_IS_NOT_ACTIVATED',
    PASSWORDS_NOT_EQUALS = 'PASSWORDS_NOT_EQUALS',
    SETTING_NOT_FOUND = 'SETTING_NOT_FOUND',
    ORGANIZATION_TO_SETTING_DUPLICATED = 'ORGANIZATION_TO_SETTING_DUPLICATED',
    ORGANIZATION_TO_SETTING_WRONG_TYPE = 'ORGANIZATION_TO_SETTING_WRONG_TYPE',
    ORGANIZATION_TO_SETTING_NOT_FOUND = 'ORGANIZATION_TO_SETTING_NOT_FOUND',
    ORGANIZATION_NOT_FOUND = 'ORGANIZATION_NOT_FOUND',
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR'
}

export enum RoutesErrors {
    SIGNUP_ERROR = 'SIGNUP_ERROR',
    LOGIN_ERROR = 'LOGIN_ERROR',
    CREATE_USER_ERROR = 'CREATE_USER_ERROR',
    UPDATE_USER_ERROR = 'UPDATE_USER_ERROR',
    DELETE_USER_ERROR = 'DELETE_USER_ERROR',
    GET_USERS_SETTINGS_ERROR = 'GET_USERS_SETTINGS_ERROR',
    GET_USERS_SETTINGS_BY_ID_ERROR = 'GET_USERS_SETTINGS_BY_ID_ERROR',
    GET_ORGANIZATION_SETTINGS_ERROR = 'GET_ORGANIZATION_SETTINGS_ERROR',
    ADD_USER_SETTINGS_ERROR = 'ADD_USER_SETTINGS_ERROR',
    UPDATE_USER_SETTINGS_BY_ID_ERROR = 'UPDATE_USER_SETTINGS_BY_ID_ERROR',
    UPDATE_ORGANIZATION_SETTINGS_ERROR = 'UPDATE_ORGANIZATION_SETTINGS_ERROR',
    DELETE_USER_SETTINGS_BY_ID_ERROR = 'DELETE_USER_SETTINGS_BY_ID_ERROR',
    DELETE_ORGANIZATION_SETTINGS_ERROR = 'DELETE_ORGANIZATION_SETTINGS_ERROR',
}

export enum StatusCodes {
    OK = 200,
    BAD_INPUT = 400,
    UNAUTHORIZED = 401,
    FORBIDDEN = 403,
    NOT_FOUND = 404,
    UNPROCESSABLE_ENTITY = 422,
    INTERNAL_SERVER_ERROR = 500,
}

export const InternalStatusCodesMap: Record<InternalCodes, StatusCodes> = {
    [InternalCodes.USER_NOT_FOUND]: StatusCodes.NOT_FOUND,
    [InternalCodes.USER_DUPLICATED]: StatusCodes.UNPROCESSABLE_ENTITY,
    [InternalCodes.USER_IS_NOT_PENDING]: StatusCodes.INTERNAL_SERVER_ERROR,
    [InternalCodes.USER_IS_NOT_ACTIVATED]: StatusCodes.INTERNAL_SERVER_ERROR,
    [InternalCodes.PASSWORDS_NOT_EQUALS]: StatusCodes.UNAUTHORIZED,
    [InternalCodes.SETTING_NOT_FOUND]: StatusCodes.NOT_FOUND,
    [InternalCodes.ORGANIZATION_TO_SETTING_DUPLICATED]: StatusCodes.UNPROCESSABLE_ENTITY,
    [InternalCodes.ORGANIZATION_TO_SETTING_WRONG_TYPE]: StatusCodes.BAD_INPUT,
    [InternalCodes.ORGANIZATION_TO_SETTING_NOT_FOUND]: StatusCodes.NOT_FOUND,
    [InternalCodes.ORGANIZATION_NOT_FOUND]: StatusCodes.NOT_FOUND,
    [InternalCodes.INTERNAL_SERVER_ERROR]: StatusCodes.INTERNAL_SERVER_ERROR,
}